### ISSUE TITLE
Error in Bot.GetMeAsync().Result

### ISSUE THREAD

**Issue by SeyedAliDehghan** [TelegramBots/telegram.bot#405] opened 2017-07-25 11:39 UTC
hi
i created my project
and every thing is like example of this library
bot when i want to run project
i get a error of this line:
            `var me = Bot.GetMeAsync().Result;`

and error is :

An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

please help me :(

**Comment by pouladpld** [comment] 2017-07-25 12:06
Add Newtonsoft.Json NuGet package reference as well.

**Comment by SeyedAliDehghan** [comment] 2017-07-25 12:07
i do it but error is still there

**Comment by Olfi01** [comment] 2017-07-26 07:14
seems you got the wrong version then i guess

**Comment by pouladpld** [comment] 2017-07-27 22:47
@SeyedAliDehghan Did you find out what the problem is? Please either close this issue or give us more info following the [issue template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md).

**Closed** 2017-07-30 13:16 UTC

**Comment by armanforghani** [comment] 2017-08-13 15:49
I have a same problem.

**Comment by gssj007** [comment] 2018-02-20 12:39
i have an error that says :
The underlying connection was closed: An unexpected error occurred on a send.
in inner says:
Authentication failed because the remote party has closed the transport stream.
what is my problem
