### ISSUE TITLE
Newline problem for image caption

### ISSUE THREAD

**Issue by p30help** [TelegramBots/telegram.bot#417] opened 2017-08-01 09:27 UTC
I use Telegram Bot Api Library (ver 13.0.1.0) in my Asp.Net project.
I use under code to send image with caption to my channel.

```
var sb = new StringBuilder(); 
sb.AppendLine("line1 "); 
sb.AppendLine("line2 "); 
sb.AppendLine("line3 ");  
bot.SendPhotoAsync("@" + channel.Name, fileToSend, sb.ToString(), false, 0);
```

But my problem is that my newline don't show in output and show like this:

> line1 \r\n line2 \r\n line3 \r\n

how can send photo with caption that support newline?

**Comment by pouladpld** [comment] 2017-08-01 10:03
Duplicate of #409

**Closed by pouladpld** 2017-08-01 10:03 UTC
Labels: duplicate
