### ISSUE TITLE
\n Not work

### ISSUE THREAD

**Issue by Hamed6380** [TelegramBots/telegram.bot#428] opened 2017-08-13 19:04 UTC
Hi
Why \n not Work in SendPhotoAsync Caption in Telegram.bot Version 13.1.0
Thanks

**Comment by pouladpld** [comment] 2017-08-13 19:18
Duplicate of #409

**Comment by pouladpld** [comment] 2017-08-13 19:19
@Hamed6380 Please do a quick search before opening a new issue.

**Closed by pouladpld** 2017-08-13 19:19 UTC
Labels: duplicate

**Comment by Hamed6380** [comment] 2017-08-13 19:38
sorry ...
