### ISSUE TITLE
SendInvoiceAsync issue

### ISSUE THREAD

**Issue by starkdm** [TelegramBots/Telegram.Bot#928] opened 2020-09-22 16:27 UTC
I am using Telegram.Bot 15.7.1 version (latest).

The invoice is not displayed and the task is not completed. What am I doing wrong?
providerToken has the following format: "123456789:TEST:54321" (Yandex.Kassa)

`botclient.SendInvoiceAsync((int)chatId, "Title", "Description", "payload", providerToken, "start_param_0", "RUB", new[] { new Telegram.Bot.Types.Payments.LabeledPrice("Label1", 1) }).Wait();`

**Comment by karb0f0s** [comment] 2020-09-23 08:52
Do you call `SendInvoiceAsync` inside an Event Handler? If so - there might be an unhandled exception that is swallowed during the run. You can put `SendInvoiceAsync` call inside `try {} catch (e) {}` block to see if anything goes wrong.
For further discovery you can take few more steps:
Behind [SendInvoiceAsync](https://github.com/TelegramBots/Telegram.Bot/blob/e09ed3f20ba6a1f05ac0ea8c2e3dccc3550a641f/src/Telegram.Bot/TelegramBotClient.cs#L1253) is simply a constructor for [SendInvoiceRequest](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/Requests/Payments/SendInvoiceRequest.cs)
Ideally you have to manually construct and serialize your request and invoke it manually against [sendinvoice](https://core.telegram.org/bots/api#sendinvoice) API with some REST tool (Postman, Insomnia etc.).
You can use this snippet to get effective JSON for your request:
```csharp
var chatId = 0;
var providerToken = "123456789:TEST:54321";
var invoiceRequest = new SendInvoiceRequest(chatId: (int)chatId,
                                     title: "Title",
                                     description: "Description",
                                     payload: "payload",
                                     providerToken: providerToken,
                                     startParameter: "start_param_0",
                                     currency: "RUB",
                                     prices: new[] {
                                         new LabeledPrice("Label1", 1)
                                     });

string payload = JsonConvert.SerializeObject(invoiceRequest);
Console.WriteLine(payload);
```
And then, it would be great if you'll find which values are serialized incorrectly, so we can fix the request for this API call.

Until then, I mark this issue as `non-reproducible`, because it works correctly [in our test suite](https://github.com/TelegramBots/Telegram.Bot/blob/c5ae749c444f62a744cc3db2a84908971a40d829/test/Telegram.Bot.Tests.Integ/Payments/PaymentTests.cs#L31-L88).

**Comment by starkdm** [comment] 2020-09-23 14:19
@karb0f0s "Do you call SendInvoiceAsync inside an Event Handler?" - What handler should be?

**Comment by karb0f0s** [comment] 2020-09-23 19:21
You have to provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so we could find out the root cause of your situation.
If you interested in further discussion, feel free to join our [support group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).
If you're unable to provide any additional information - I will close this issue.

**Comment by Eugene1700** [comment] 2021-01-22 17:08
You must change you prices, because you choose currency "RUB". If you want to send invoice with 100 rub - set 10000 (min amount is 100 rub), because minimal currency item is kopek(1 rub = 100 kopek).

**Closed** 2021-02-11 13:52 UTC
Labels: area-payments
