### ISSUE TITLE
### Problem in caption of image in version 13

### ISSUE THREAD

**Issue by payam-rsh** [TelegramBots/telegram.bot#419] opened 2017-08-05 11:32 UTC
### Environment data

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by payam-rsh** [comment] 2017-08-05 11:34
when i send some text that contains new line char , in caption of SendPhotoAsync method ,
text that recived with \r or \n or \r\n charackters isntead new line in text.
please help me

**Comment by webiox** [comment] 2017-08-05 12:29
I have the exactly same problem, and I've just figured out that it works great when I pass a stored fileID as "FileToSend" parameter value to "SendPhotoAsync". 
The problem occurs when I try to pass a Stream of my photo to "SendPhotoAsync".

**Comment by payam-rsh** [comment] 2017-08-05 12:39
thanks , this solution worked for me.

**Comment by pouladpld** [comment] 2017-08-05 12:44
Duplicate of #409

**Closed** 2017-08-05 12:44 UTC
Labels: duplicate
