### ISSUE TITLE
Making requests when getting updates

### ISSUE THREAD

**Issue by 9px** [TelegramBots/Telegram.Bot#36] opened 2015-09-05 18:03 UTC
hi. telegram [recently](https://core.telegram.org/bots/api#making-requests-when-getting-updates) add an ability to perform a request to the telegram Bot API while sending an answer to the webhook.
can you do a simple implement of this feature in your bot?

**Comment by MrRoundRobin** [comment] 2016-01-13 18:31
i'm working on this, but currently i'm not sure how i'll implement it.

**Comment by a-a-k** [comment] 2016-04-02 11:48
Hi,
could you show some samples of your work version to us?

**Comment by mhverbakel** [comment] 2016-07-06 09:14
The problem is that the called methods are all plain dictionaries at the moment. To be able to return them in MVC for example, you would need to switch to classes for method calls, and return an instance of that class using `this.Json(instance)` (in MVC).

Another option is making internal helper methods that generate the request parameters, and exposing them through public methods. Where you usually return with a `return SendWebRequestAsync`, you replace that by setting the `method` parameter and returning the dictionary. The client of the library can then handle outputting that in the webhook response.

**Comment by mikhail-mikhaylov** [comment] 2016-12-17 19:29
Maybe it's better to just return instance of some class that represents http response?
I mean some custom class, not HttpResponseMessage.
This class will have string body property, and some properies with headers. 
This would hide all implementation details and would not expose dictionary to the client.

**Comment by Olfi01** [comment] 2017-09-06 12:26
I have looked into this, and it seems that you've just got to return a json-encoded object containing all the parameters and the method name. So how about just adding a class for that? I'll try to do something like that.

**Comment by tuscen** [comment] 2020-07-24 00:03
Fixed by #847.

**Closed by tuscen** 2020-07-24 00:03 UTC
Labels: help wanted
