### ISSUE TITLE
Sendphoto parse mode not working

### ISSUE THREAD

**Issue by navaei** [TelegramBots/telegram.bot#436] opened 2017-08-20 11:25 UTC
when sending photo with a stream text parse mode not working.
for example \n\n pure display in the photo caption.
but for saved photo in telegram server(send by photo id) is that correctly working.

**Comment by pouladpld** [comment] 2017-08-20 12:07
Duplicate of #409

**Comment by pouladpld** [comment] 2017-08-20 12:08
@navaei please do a quick search before openning a new issue.

**Closed by pouladpld** 2017-08-20 12:07 UTC
