### ISSUE TITLE
ITelegramBotClient.SendTextMessageAsync() System.Text.Json Polymorphic Type Resolving Exception

### ISSUE THREAD

**Issue by cbagpipe** [TelegramBots/Telegram.Bot#1402] opened 2024-07-16 11:19 UTC
### Steps to reproduce

- Create simple console app
- Create instance of `TelegramBotClient`
- add usage of `SendTextMessageAsync` method
- add     
```xml
<PublishSingleFile>true</PublishSingleFile>
<SelfContained>true</SelfContained>
<PublishTrimmed>true</PublishTrimmed>
```
to csproj
- publish app
- run published app

### Expected  behavior

Message sent to provided id

### Actual behavior

Crash with following Exception
```
Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.Serialize(Object , Type, JsonSerializerOptions )
   at Telegram.Bot.Requests.RequestBase`1.ToHttpContent()
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1, CancellationToken )
   at Telegram.Bot.TelegramBotClientExtensions.SendTextMessageAsync(ITelegramBotClient , ChatId , String , Nullable`1 , ParseMode , IEnumerable`1 , LinkPreviewOptions , Boolean , Boolean , String , ReplyParameters , IReplyMarkup , String , CancellationToken )
   at monitor.TelegramNotifier.Send(String, String) in /home/cb/monitor/TelegramNotifier.cs:line 25
   at monitor.Program.Main(String[]) in /home/cb/monitor/Program.cs:line 81
   at monitor.Program.<Main>(String[])
```

### Environment data

*NuGet Package Version:*  21.6.2

*.NET Version:* 8

*IDE:* VS Code on Linux

*App:* Simple console app, built as single-file, self-contained and trimmed

**Comment by wiz0u** [comment] 2024-07-16 11:54
We don't support trimming yet.

Duplicate of #1322

**Comment by wiz0u** [comment] 2024-07-16 11:54
Duplicate of #1322

**Closed by wiz0u** 2024-07-16 11:54 UTC
